### ISSUE TITLE
Update google analytics integration

### ISSUE THREAD

**Issue by drorata** [haoadoresorange/haoadores.comtam.dev#1]
@haoadoreorange I understand that in https://github.com/haoadoreorange/h4o.dev/commit/98b6e68d42926ca3ffb363c5515d99923f8f73e9 you updated the way Google Analytics is integrated into your blog. The following is the code you're currently using in your template:

https://github.com/haoadoreorange/h4o.dev/blob/98b6e68d42926ca3ffb363c5515d99923f8f73e9/theme/templates/_base.html#L59-L69

correct?

Does it work for you? Were there other changes you had to do?

PS: How did you validate that the change works?

**Comment by haoadoreorange** [comment]
Hi, yeah I just copied the snippet following google's instructions. Dont remember modifying anything :-?

And to verify I just check on the analytics console (:

I was supposed to write a blog abt this too but was tooo occupied to get it done ):

**Comment by drorata** [comment]
Thanks a lot! It worked for me nicely. I think :)
